//
// Generated file, do not edit! Created by nedtool 4.6 from DL_PDU.msg.
//

#ifndef _DL_PDU_M_H_
#define _DL_PDU_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>DL_PDU.msg:19</tt> by nedtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * packet DL_PDU
 * {
 *     int Id;
 *     int sc;
 *     int dst;
 * }
 * </pre>
 */
class DL_PDU : public ::cPacket
{
  protected:
    int Id_var;
    int sc_var;
    int dst_var;

  private:
    void copy(const DL_PDU& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const DL_PDU&);

  public:
    DL_PDU(const char *name=NULL, int kind=0);
    DL_PDU(const DL_PDU& other);
    virtual ~DL_PDU();
    DL_PDU& operator=(const DL_PDU& other);
    virtual DL_PDU *dup() const {return new DL_PDU(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getId() const;
    virtual void setId(int Id);
    virtual int getSc() const;
    virtual void setSc(int sc);
    virtual int getDst() const;
    virtual void setDst(int dst);
};

inline void doPacking(cCommBuffer *b, DL_PDU& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, DL_PDU& obj) {obj.parsimUnpack(b);}


#endif // ifndef _DL_PDU_M_H_

